import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/pages/NavBar";
import Footer from "@/components/pages/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className="min-h-screen bg-[#0a0c10] 
    bg-[linear-gradient(to_right,rgba(0,102,255,0.1)_1px,transparent_1px),linear-gradient(to_bottom,rgba(0,102,255,0.1)_1px,transparent_1px)] 
    bg-[size:40px_40px]"
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
